from building import *

cwd = GetCurrentDir()

src = Glob('./*.c')

path =  [cwd,
         os.path.join(cwd, '../include')]

group = DefineGroup('Drivers', src, depend = ['BSP_USING_BOARD_IWATCH_SF32LB58_A128_QSPI'], CPPPATH = path)

if GetDepend('BSP_USING_BOARD_IWATCH_SF32LB58_A128_QSPI'):
    group = group + SConscript('../sf32lb58-lcd_base/script/SConscript')

Return('group')
