from building import *
import os
font_objs = []

cwd = GetCurrentDir()
font_file = os.path.join(cwd, 'DroidSansFallback.ttf')


if not os.path.exists(font_file):
    print(f"Whether memory allocation is dynamic: Warning: Font file does not exist: {font_file}")
    font_objs = []
else:
    print(f"Font file path: {font_file}")
    font_objs = Env.ConvertFont(font_file, 'DroidSansFallback')
    font_objs = DefineGroup('resource', font_objs, depend = ['PKG_USING_LITTLEVGL2RTT'])



Return('font_objs')