/*
 * SPDX-FileCopyrightText: 2019-2022 SiFli Technologies(Nanjing) Co., Ltd
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include "bsp_board.h"
#include "bf0_hal_pinmux.h"

#ifdef BSP_USING_SDHCI1
void BSP_sd1_pinmux_config()
{
    HAL_PIN_Set(PAD_PA39, SD1_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA41, SD1_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA30, SD1_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA36, SD1_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA40, SD1_DIO3, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA38, SD1_DIO4, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA37, SD1_DIO5, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA35, SD1_DIO6, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA33, SD1_DIO7, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA34, SD1_CMD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA49, GPIO_A49, PIN_PULLUP, 1);     // SD1 RESET, need set 0 first?
    HAL_PIN_Set(PAD_PA80, GPIO_A80, PIN_PULLUP, 1);     // SD1 EN
}
#endif
#ifdef BSP_USING_SDHCI2
void BSP_sd2_pinmux_config()
{
    HAL_PIN_Set(PAD_PA70, SD2_CMD,  PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA75, SD2_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA76, SD2_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA77, SD2_CLK,  PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA79, SD2_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA81, SD2_DIO3, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA58, GPIO_A58, PIN_NOPULL, 1);     // SD1 card detect pin
}
#endif

static void config_psram_pinmux(void)
{
    if (CHIP_IS_583())
    {
        // PSRAM1
        HAL_PIN_Set(PAD_SA04, MPI1_DIO0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA05, MPI1_DIO1, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA06, MPI1_DIO2, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA07, MPI1_DIO3, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA09, MPI1_CS,  PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SA10, MPI1_CLK,   PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SA11, MPI1_DIO4, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA12, MPI1_DIO5, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA13, MPI1_DIO6, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA14, MPI1_DIO7, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA15, MPI1_DQS0,  PIN_PULLDOWN, 1);

        // PSRAM2
        HAL_PIN_Set(PAD_SB04, MPI2_DIO0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB05, MPI2_DIO1, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB06, MPI2_DIO2, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB07, MPI2_DIO3, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB09, MPI2_CS,  PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SB10, MPI2_CLK,   PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SB11, MPI2_DIO4, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB12, MPI2_DIO5, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB13, MPI2_DIO6, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB14, MPI2_DIO7, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB15, MPI2_DQS0,  PIN_PULLDOWN, 1);
    }
    else if (CHIP_IS_587())
    {
        // PSRAM1
        HAL_PIN_Set(PAD_SA00, MPI1_DIO0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA01, MPI1_DIO1, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA02, MPI1_DIO2, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA03, MPI1_DIO3, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA04, MPI1_DIO4, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA05, MPI1_DIO5, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA06, MPI1_DIO6, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA07, MPI1_DIO7, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA08, MPI1_DQS0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA09, MPI1_CLK,   PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SA10, MPI1_CS,  PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SA11, MPI1_DIO8, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA12, MPI1_DIO9, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA13, MPI1_DIO10, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA14, MPI1_DIO11, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA15, MPI1_DIO12, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA16, MPI1_DIO13, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA17, MPI1_DIO14, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA18, MPI1_DIO15, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SA19, MPI1_DQS1, PIN_PULLDOWN, 1);

        // PSRAM2
        HAL_PIN_Set(PAD_SB00, MPI2_DIO0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB01, MPI2_DIO1, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB02, MPI2_DIO2, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB03, MPI2_DIO3, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB04, MPI2_DIO4, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB05, MPI2_DIO5, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB06, MPI2_DIO6, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB07, MPI2_DIO7, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB08, MPI2_DQS0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB09, MPI2_CLK,   PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SB10, MPI2_CS,  PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SB11, MPI2_DIO8, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB12, MPI2_DIO9, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB13, MPI2_DIO10, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB14, MPI2_DIO11, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB15, MPI2_DIO12, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB16, MPI2_DIO13, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB17, MPI2_DIO14, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB18, MPI2_DIO15, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB19, MPI2_DQS1, PIN_PULLDOWN, 1);
    }
    else if (CHIP_IS_585())
    {
        // PSRAM2
        HAL_PIN_Set(PAD_SB00, MPI2_DIO0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB01, MPI2_DIO1, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB02, MPI2_DIO2, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB03, MPI2_DIO3, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB04, MPI2_DIO4, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB05, MPI2_DIO5, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB06, MPI2_DIO6, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB07, MPI2_DIO7, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB08, MPI2_DQS0, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB09, MPI2_CLK,   PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SB10, MPI2_CS,  PIN_NOPULL, 1);
        HAL_PIN_Set(PAD_SB11, MPI2_DIO8, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB12, MPI2_DIO9, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB13, MPI2_DIO10, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB14, MPI2_DIO11, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB15, MPI2_DIO12, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB16, MPI2_DIO13, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB17, MPI2_DIO14, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB18, MPI2_DIO15, PIN_PULLDOWN, 1);
        HAL_PIN_Set(PAD_SB19, MPI2_DQS1, PIN_PULLDOWN, 1);
    }
}


void BSP_PIN_Init(void)
{
#ifdef SOC_BF0_HCPU
    // HCPU pins
    config_psram_pinmux();

    HAL_PIN_Set(PAD_PA16, GPIO_A16, PIN_NOPULL, 1);//TP rst
    HAL_PIN_Set(PAD_PA17, GPIO_A17, PIN_NOPULL, 1);//TP irq
    HAL_PIN_Set(PAD_PA18, GPIO_A18, PIN_PULLDOWN, 1);//LCD rst

    // I2C1 for touch panel
    HAL_PIN_Set(PAD_PA59, I2C4_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA60, I2C4_SCL, PIN_PULLUP, 1);
    // I2C3 for PA
    HAL_PIN_Set(PAD_PA93, I2C3_SDA, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA92, I2C3_SCL, PIN_PULLUP, 1);

    //PA
    HAL_PIN_Set(PAD_PA88, GPIO_A88, PIN_PULLDOWN, 1);

#ifdef BSP_ENABLE_MPI4
    HAL_PIN_Set(PAD_PA39, MPI4_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA30, MPI4_CS, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA40, MPI4_DIO0, PIN_PULLDOWN, 1);
    HAL_PIN_Set(PAD_PA37, MPI4_DIO1, PIN_PULLDOWN, 1);
    HAL_PIN_Set(PAD_PA36, MPI4_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA38, MPI4_DIO3, PIN_PULLUP, 1);
#endif
#ifdef BSP_ENABLE_MPI3
    //TODO: power pin
    //BSP_GPIO_Set(MPI1_POWER_PIN, 1, 1);
    //BSP_GPIO_Set(MPI2_POWER_PIN, 1, 1);
    //BSP_GPIO_Set(MPI3_POWER_PIN, 1, 1);

    // MPI3
    HAL_PIN_Set(PAD_PA46, MPI3_CLK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, MPI3_CS, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, MPI3_DIO0, PIN_PULLDOWN, 1);
    HAL_PIN_Set(PAD_PA48, MPI3_DIO1, PIN_PULLDOWN, 1);
    HAL_PIN_Set(PAD_PA47, MPI3_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA45, MPI3_DIO3, PIN_PULLUP, 1);

#endif

    // UART1
    HAL_PIN_Set(PAD_PA31, USART1_TXD, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA32, USART1_RXD, PIN_PULLUP, 1);

    // I2S2
#if defined(BSP_ENABLE_I2S_CODEC)
    HAL_PIN_Set(PAD_PA82, I2S2_SDO, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA91, I2S2_BCK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA84, I2S2_LRCK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA86, I2S2_SDI, PIN_PULLDOWN, 1);
#endif
    // I2S3
#if defined(BSP_ENABLE_I2S3)
    HAL_PIN_Set(PAD_PB24, I2S3_SDO, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB30, I2S3_BCK, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB31, I2S3_LRCK, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB27, I2S3_SDI, PIN_PULLDOWN, 0);
#endif

#ifdef BSP_USING_PDM1
    // PDM1
    HAL_PIN_Set(PAD_PA24, GPIO_A24, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA23, PDM1_CLK, PIN_NOPULL, 1);
    //HAL_PIN_Set(PAD_PA18, PDM1_DATA, PIN_PULLDOWN, 1);
    //I2S1
#elif defined(BSP_ENABLE_I2S_MIC)
    HAL_PIN_Set(PAD_PA14, I2S1_LRCK, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA23, I2S1_BCK, PIN_NOPULL, 1);
    //HAL_PIN_Set(PAD_PA18, I2S1_SDI, PIN_PULLDOWN, 1);
#endif

    // UART2
    HAL_PIN_Set(PAD_PA28, USART2_TXD, PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA29, USART2_RXD, PIN_PULLUP, 1);

    // LCDC1
#if 0//def BSP_LCDC_USING_DBI
    HAL_PIN_Set(PAD_PA20, LCDC1_8080_WR, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA31, LCDC1_8080_CS, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA34, LCDC1_8080_RD, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA36, LCDC1_8080_DC, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA38, LCDC1_8080_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA42, LCDC1_8080_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_8080_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_8080_DIO3, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_8080_DIO4, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA49, LCDC1_8080_DIO5, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA51, LCDC1_8080_DIO6, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA55, LCDC1_8080_DIO7, PIN_PULLUP, 1);

    HAL_PIN_Set(PAD_PA77, LCDC1_8080_TE, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA78, LCDC1_8080_RSTB, PIN_PULLUP, 1);
#elif 0//defined(BSP_LCDC_USING_JDI_PARALLEL) Always use LPSYS JDI
    HAL_PIN_Set(PAD_PA19, LCDC1_JDI_VCK, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA22, LCDC1_JDI_VST, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA25, LCDC1_JDI_XRST, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA43, LCDC1_JDI_HCK, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_JDI_HST, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_JDI_ENB, PIN_PULLUP, 1);
    //HAL_PIN_Set(PAD_PA42, LCDC1_JDI_DIO1, PIN_PULLUP, 1);
    //HAL_PIN_Set(PAD_PA44, LCDC1_JDI_FRP, PIN_PULLUP, 1);
    //HAL_PIN_Set(PAD_PA45, LCDC1_JDI_XFRP, PIN_PULLUP, 1);
    //HAL_PIN_Set(PAD_PA47, LCDC1_JDI_VCOM, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA46, LCDC1_JDI_R1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_JDI_R2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_JDI_G1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_JDI_G2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA65, LCDC1_JDI_B1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA67, LCDC1_JDI_B2, PIN_PULLUP, 1);
#elif defined(BSP_LCDC_USING_DPI)
    HAL_PIN_Set(PAD_PA12, LCDC1_DPI_CLK,    PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA13, LCDC1_DPI_DE,     PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA14, LCDC1_DPI_HSYNC,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA15, LCDC1_DPI_VSYNC,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA22, LCDC1_DPI_R0,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA23, LCDC1_DPI_R1,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA24, LCDC1_DPI_R2,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA25, LCDC1_DPI_R3,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA26, LCDC1_DPI_R4,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA27, LCDC1_DPI_R5,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA43, LCDC1_DPI_R6,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_DPI_R7,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_DPI_G0,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA46, LCDC1_DPI_G1,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_DPI_G2,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_DPI_G3,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_DPI_G4,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA53, LCDC1_DPI_G5,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA54, LCDC1_DPI_G6,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA55, LCDC1_DPI_G7,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA56, LCDC1_DPI_B0,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA57, LCDC1_DPI_B1,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA58, LCDC1_DPI_B2,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA61, LCDC1_DPI_B3,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA62, LCDC1_DPI_B4,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA63, LCDC1_DPI_B5,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA65, LCDC1_DPI_B6,  PIN_NOPULL, 1);
    HAL_PIN_Set(PAD_PA67, LCDC1_DPI_B7,  PIN_NOPULL, 1);
    //HAL_PIN_Set(PAD_PA67, LCDC1_DPI_CM,  PIN_NOPULL, 1);
#elif defined(BSP_LCDC_USING_QADSPI)
    HAL_PIN_Set(PAD_PA46, LCDC1_SPI_CLK, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA44, LCDC1_SPI_CS, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA50, LCDC1_SPI_DIO0, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA48, LCDC1_SPI_DIO1, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA47, LCDC1_SPI_DIO2, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA45, LCDC1_SPI_DIO3, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA43, LCDC1_SPI_TE, PIN_PULLUP, 1);
    HAL_PIN_Set(PAD_PA18, GPIO_A18, PIN_NOPULL, 1); //LCD rst
#endif

    HAL_PIN_Set(PAD_PA42, GPTIM2_CH4, PIN_NOPULL, 1); //LCD backlight PWM( DSI&DPI LCD)

    /*SDHCI1 config*/
#ifdef BSP_USING_SDHCI1
    BSP_sd1_pinmux_config();
#endif

    /*SDHCI2 config*/
#ifdef BSP_USING_SDHCI2
    BSP_sd2_pinmux_config();
#endif
    if (PM_STANDBY_BOOT != SystemPowerOnModeGet())
    {
        HAL_PBR0_FORCE1_ENABLE();
    }
#endif

    // LCPU pins
    HAL_PIN_Set(PAD_PB14, USART6_TXD, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB13, USART6_RXD, PIN_PULLUP, 0);

    // PTC debug pin
    HAL_PIN_Set(PAD_PB18, GPIO_B18, PIN_NOPULL, 0);

    // PA CTRL PIN
    HAL_PIN_Set(PAD_PB23, GPIO_B23, PIN_NOPULL, 0);

    HAL_PIN_Set(PAD_PB32, ANA_PIN_FUNC, PIN_NOPULL, 0); // AUD RESET USED AS ADC 0 , remove it if audio i2s3 use reset
    HAL_PIN_Set(PAD_PB34, ANA_PIN_FUNC, PIN_NOPULL, 0); // AUD MCLK, USED AS GPADC CH2
    HAL_PIN_Set(PAD_PB33, ANA_PIN_FUNC, PIN_NOPULL, 0); // NTC GPADC CH1
    HAL_PIN_Set(PAD_PB35, ANA_PIN_FUNC, PIN_NOPULL, 0); // VBAT GPADC CH3
#if defined(SOC_BF0_LCPU)
    HAL_PIN_Set_Analog(PAD_PB32, 0);
    HAL_PIN_Set_Analog(PAD_PB33, 0);
    HAL_PIN_Set_Analog(PAD_PB34, 0);
    HAL_PIN_Set_Analog(PAD_PB35, 0);

#endif

    // Key1
    HAL_PIN_Set(PAD_PB54, GPIO_B43, PIN_NOPULL, 0);

    HAL_PIN_Set(PAD_PB37, USART4_TXD, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB36, USART4_RXD, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB18, USART5_TXD, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB17, USART5_RXD, PIN_PULLUP, 0);

    // I2C5
    HAL_PIN_Set(PAD_PB48, I2C5_SCL, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB47, I2C5_SDA, PIN_PULLUP, 0);

    // I2C6
    HAL_PIN_Set(PAD_PB28, I2C6_SCL, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB29, I2C6_SDA, PIN_PULLUP, 0);

#if 0
    //TODO:
    HAL_PIN_Set(PAD_PB12, SPI4_CLK, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB19, SPI4_CS, PIN_NOPULL, 0);
    HAL_PIN_Set(PAD_PB15, SPI4_DI, PIN_PULLDOWN, 0);
    HAL_PIN_Set(PAD_PB16, SPI4_DO, PIN_NOPULL, 0);
#endif

#if defined(BSP_LCDC_USING_JDI_PARALLEL)
    HAL_PIN_Set(PAD_PB15, LCDC2_JDI_VCK, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB19, LCDC2_JDI_VST, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB16, LCDC2_JDI_XRST, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB05, LCDC2_JDI_HCK, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB10, LCDC2_JDI_HST, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB12, LCDC2_JDI_ENB, PIN_PULLUP, 0);
    //HAL_PIN_Set(PAD_PB42, LCDC2_JDI_DIO1, PIN_PULLUP, 0);
    //HAL_PIN_Set(PAD_PB44, LCDC2_JDI_FRP, PIN_PULLUP, 0);
    //HAL_PIN_Set(PAD_PB45, LCDC2_JDI_XFRP, PIN_PULLUP, 0);
    //HAL_PIN_Set(PAD_PB47, LCDC2_JDI_VCOM, PIN_PULLUP, 0);
    /*
        lcdc_jdi_frp  ---- PBR3
        lcdc_jdi_xfrp ---- PBR4
        lcdc_jdi_vcom ---- PBR5
    */
    HAL_PIN_Set(PAD_PB09, LCDC2_JDI_R1, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB06, LCDC2_JDI_R2, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB08, LCDC2_JDI_G1, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB04, LCDC2_JDI_G2, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB02, LCDC2_JDI_B1, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB03, LCDC2_JDI_B2, PIN_PULLUP, 0);
#else
    /*LCD SPI*/
    HAL_PIN_Set(PAD_PB02, LCDC2_SPI_TE,   PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB03, LCDC2_SPI_DIO1, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB04, LCDC2_SPI_DIO2, PIN_PULLUP, 0);
    //HAL_PIN_Set(PAD_PB05, LCDC2_SPI_RSTB, PIN_PULLUP, 0); Use default gpio mode
    HAL_PIN_Set(PAD_PB06, LCDC2_SPI_DIO3, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB08, LCDC2_SPI_CS,   PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB09, LCDC2_SPI_DIO0, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB10, LCDC2_SPI_CLK,  PIN_PULLUP, 0);
#endif

#if !defined(BSP_LCDC_USING_JDI_PARALLEL)
    HAL_PIN_Set(PAD_PB12, SPI4_CLK, PIN_PULLDOWN, 0);             // SPI4 (GSensor)
    HAL_PIN_Set(PAD_PB15, SPI4_DI, PIN_PULLDOWN, 0);
    HAL_PIN_Set(PAD_PB16, SPI4_DO, PIN_PULLDOWN, 0);
    HAL_PIN_Set(PAD_PB19, SPI4_CS, PIN_PULLUP, 0);
#endif
    HAL_PIN_Set(PAD_PB59, GPIO_B59, PIN_NOPULL, 0);             // SPI4_EN

    HAL_PIN_Set(PAD_PB28, I2C6_SCL, PIN_PULLUP, 0);             // I2C6 (Heart rate sensor)
    HAL_PIN_Set(PAD_PB29, I2C6_SDA, PIN_PULLUP, 0);
    HAL_PIN_Set(PAD_PB39, GPIO_B39, PIN_NOPULL, 0);              // Heart power
    HAL_PIN_Set(PAD_PB57, GPIO_B57, PIN_NOPULL, 0);              // hrt INT
    HAL_PIN_Set(PAD_PB53, GPIO_B53, PIN_PULLUP, 0);     //BSP_CHARGER_EN_PIN
    HAL_PIN_Set(PAD_PB47, GPIO_B47, PIN_PULLUP, 0);     //BSP_CHARGE_FULL_PIN
    HAL_PIN_Set(PAD_PB48, GPIO_B48, PIN_PULLUP, 0);     //BSP_CHARGING_PIN
    HAL_PIN_Set(PAD_PB56, GPIO_B56, PIN_PULLDOWN, 0);     //BSP_CHARGER_INT_PIN   INT

}
