CONFIG_BSP_USING_ENCODER=y
CONFIG_BSP_USING_ONCHIP_RTC=y
CONFIG_RT_MAIN_THREAD_STACK_SIZE=4096
CONFIG_RT_MAIN_THREAD_PRIORITY=19
CONFIG_RT_USING_DFS_ELMFAT=y
CONFIG_RT_SERIAL_RB_BUFSZ=256
CONFIG_RT_USING_HWMAILBOX=y
CONFIG_RT_USING_ULOG=y
CONFIG_ULOG_USING_ISR_LOG=y
CONFIG_ULOG_OUTPUT_FLOAT=y
# CONFIG_ULOG_USING_COLOR is not set
CONFIG_ULOG_OUTPUT_THREAD_NAME=y
CONFIG_RT_USING_MEMHEAP=y
CONFIG_RT_USING_MEMTRACE=y
CONFIG_BSP_USING_FULL_ASSERT=y
CONFIG_USING_CELL_TRANSFORM=y
CONFIG_GUI_APP_FRAMEWORK=y
CONFIG_USING_BUTTON_LIB=y
CONFIG_USING_CPU_USAGE_PROFILER=y
CONFIG_USING_EZIPA_DEC=y
CONFIG_PKG_USING_LITTLEVGL2RTT=y
CONFIG_LVGL_V9=y
CONFIG_LV_USING_EXT_RESOURCE_MANAGER=y
CONFIG_LV_FONT_MONTSERRAT_12=y
# CONFIG_LV_FONT_MONTSERRAT_14 is not set
CONFIG_LV_FONT_MONTSERRAT_20=y
CONFIG_LV_FONT_MONTSERRAT_24=y
CONFIG_LV_FONT_MONTSERRAT_28=y
CONFIG_LV_FONT_MONTSERRAT_36=y
CONFIG_LV_FONT_DEFAULT_MONTSERRAT_16=y
# CONFIG_LV_USE_THEME_DEFAULT is not set
CONFIG_LV_USE_FS_POSIX=y
CONFIG_LV_FS_POSIX_LETTER=65
CONFIG_LV_USE_QRCODE=y
CONFIG_LV_USE_SNAPSHOT=y
CONFIG_LV_USE_FLOAT=y
CONFIG_LV_USE_PRIVATE_API=y
CONFIG_LV_USE_TINY_TTF=y
CONFIG_LV_TINY_TTF_FILE_SUPPORT=y
CONFIG_TINY_TTF_CACHE_SIZE=160000
CONFIG_LV_USE_EZIP=y
CONFIG_LV_EXT_RES_NON_STANDALONE=y
CONFIG_LV_FB_TWO_NOT_SCREEN_SIZE=y
CONFIG_LV_FB_LINE_NUM=50
CONFIG_IMAGE_CACHE_IN_SRAM_SIZE=50000
