import os
from building import *

cwd = GetCurrentDir()
objs = []
list = os.listdir(cwd)

# Add SDK
Import('SIFLI_SDK')
objs.extend(SConscript(os.path.join(SIFLI_SDK, 'SConscript'), variant_dir="sifli_sdk", duplicate=0))

# Add application source code
# workaround: src folder must be created before resource/strings folder is used, otherwise langpack would not be built
Execute(Mkdir('src'))
objs.extend(SConscript(cwd+'/../src/SConscript', variant_dir="src", duplicate=0))

Return('objs')
