# for module compiling
import os
from building import *
import rtconfig

cwd = GetCurrentDir()
list = os.listdir(cwd)
objs = []

if GetDepend('PKG_USING_LITTLEVGL2RTT'):
	objs = Glob('*.c')
	group = DefineGroup('App_watch_demo', objs, depend = ['PKG_USING_LITTLEVGL2RTT'], CPPPATH = [''], LOCAL_CCFLAGS = '')
	for d in list:
	    path = os.path.join(cwd, d)
	    if os.path.isfile(os.path.join(path, 'SConscript')):
	        objs = objs + SConscript(os.path.join(d, 'SConscript'))
Return('objs')
