/* 使用浏览器验证静态图册并输出可直接查看的审核总览，不改变原始图片。 */
const fs = require('node:fs');
const path = require('node:path');
const {pathToFileURL} = require('node:url');
const {chromium} = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = path.resolve(__dirname,'../..');
const output = path.join(root,'docs/assets/watchos26-review');
const reference = path.join(root,'docs/ui/Apple_Watch官方视觉图册_待审核_v1.html');
const chosen = ['S0701_basGridView','S0702_basListView','S4700_timSetTimer','S4701_timCustomTimer','S4600_stpwStopwatch','S0400_alAddAlarm','S6502_persDisplayBright','S0731_basCCStatusTop','S0528_faces_Modular'];
(async()=>{
  const browser = await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
  const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1});
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.goto(pathToFileURL(reference).href);
  await page.waitForFunction(()=>window.WATCH_REVIEW_IMAGES?.length>0);
  await page.evaluate((names)=>{
    const byId=new Map(window.WATCH_REVIEW_IMAGES.map(i=>[i.id,i]));
    document.querySelector('#search').value='';
    document.querySelector('[data-filter="all"]').click();
    document.querySelectorAll('.reference-card').forEach(c=>{if(!names.some(n=>byId.get(c.dataset.id).original_name.includes(n)))c.remove();});
    document.querySelector('.toolbar').style.display='none';
    document.querySelector('#filter-note').textContent='Apple 官方原始配图 · watchOS 26 中文指南 · 不裁切、不改色 · 供复刻目标审核';
    document.querySelector('#result-count').textContent='重点页面总览 · 详细来源与逐图审核见完整图册';
    document.querySelector('#review-board h2').textContent='苹果原图：布局应以这些为起点';
    document.querySelector('#export').style.display='none';
    document.querySelectorAll('img').forEach(i=>i.loading='eager');
  },chosen);
  await page.waitForFunction(()=>[...document.querySelectorAll('#gallery img')].every(i=>i.complete&&i.naturalWidth>0),null,{timeout:60000});
  await page.locator('#review-board').screenshot({path:path.join(output,'official-core-board.png')});
  await page.goto(pathToFileURL(reference).href+'?view=apps');
  await page.evaluate(()=>{document.querySelectorAll('img').forEach(i=>i.loading='eager');document.querySelector('.toolbar').style.display='none';document.querySelector('#export').style.display='none';document.querySelector('#review-board h2').textContent='50 个 Apple Watch 官方 App 图标';});
  await page.waitForFunction(()=>[...document.querySelectorAll('#gallery img')].every(i=>i.complete&&i.naturalWidth>0),null,{timeout:60000});
  await page.locator('#review-board').screenshot({path:path.join(output,'official-app-icons.png')});
  await page.locator('[data-open]').first().click();
  const dialogOpen=await page.locator('#lightbox').evaluate(e=>e.open);
  await page.locator('#decision').selectOption('revise');
  await page.locator('#comment').fill('仅用于隔离浏览器验证的审核备注');
  await page.locator('#close').click();
  await page.reload();
  await page.locator('[data-open]').first().click();
  const reviewPersisted=(await page.locator('#comment').inputValue())==='仅用于隔离浏览器验证的审核备注';
  await page.locator('#close').click();
  const downloadPromise=page.waitForEvent('download');
  await page.locator('#export').click();
  const download=await downloadPromise;
  const reviewExport=JSON.parse(fs.readFileSync(await download.path(),'utf8'));
  const reviewExportValid=reviewExport.items.some(i=>i.decision==='revise'&&i.source_url.startsWith('https://help.apple.com/assets/'));
  await page.goto(pathToFileURL(reference).href+'?view=all');
  await page.evaluate(()=>document.querySelectorAll('img').forEach(i=>i.loading='eager'));
  await page.waitForFunction(()=>[...document.images].filter(i=>i.id!=='detail-img').every(i=>i.complete),null,{timeout:60000});
  const badImages=await page.evaluate(()=>[...document.querySelectorAll('#gallery img')].filter(i=>!i.naturalWidth).map(i=>i.src));
  const loaded=await page.locator('#gallery img').count();
  await page.setViewportSize({width:390,height:844});
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  await page.screenshot({path:path.join(output,'mobile-gallery-check.png')});
  const proposal=path.join(root,'docs/ui/Apple_Watch_390x450视觉提案_待审核_v1.html');
  let proposalResult=null;
  if(fs.existsSync(proposal)){
    await page.setViewportSize({width:1440,height:1100});
    await page.goto(pathToFileURL(proposal).href);
    await page.waitForFunction(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0),null,{timeout:60000});
    await page.locator('#proposal-board').screenshot({path:path.join(output,'proposal-390x450-board.png')});
    proposalResult=await page.evaluate(()=>({screens:[...document.querySelectorAll('#proposals .watch-screen')].map(e=>({id:e.dataset.proposal,width:e.offsetWidth,height:e.offsetHeight})),broken_images:[...document.images].filter(i=>!i.naturalWidth).map(i=>i.src)}));
    await page.setViewportSize({width:390,height:844});
    proposalResult.mobile_horizontal_overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  }
  const report={checked_at:new Date().toISOString(),loaded_images:loaded,bad_images:badImages,script_errors:errors,lightbox_opened:dialogOpen,review_persisted:reviewPersisted,review_export_valid:reviewExportValid,mobile_horizontal_overflow:overflow,proposal:proposalResult};
  fs.writeFileSync(path.join(output,'browser-check.json'),JSON.stringify(report,null,2)+'\n');
  console.log(JSON.stringify(report,null,2));await browser.close();
  if(badImages.length||errors.length||overflow||!dialogOpen||!reviewPersisted||!reviewExportValid||proposalResult?.mobile_horizontal_overflow||proposalResult?.screens.some(s=>s.width!==390||s.height!==450))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1;});
