#include "iw_routes.h"

/* 只冻结身份和准入，不为未实现的产品页伪造可用状态。诊断参数按值传递。 */
#define PAGE(id, app, parent, cap, support, resume) \
    {IW_PAGE_##id, IW_APP_##app, parent, IW_ROUTE_CAP_DISPLAY | (cap), \
     IW_ROUTE_##support, IW_RESUME_##resume, \
     IW_ROUTE_##support == IW_ROUTE_READY ? IW_ROUTE_STATE_CONTENT | IW_ROUTE_STATE_ERROR | IW_ROUTE_STATE_UNAVAILABLE : 0, \
     IW_ROUTE_##support == IW_ROUTE_READY ? (IW_APP_##app == IW_APP_ALARM || IW_PAGE_##id == IW_PAGE_ALERT_TIMER || IW_PAGE_##id == IW_PAGE_ALERT_ALARM ? IW_ROUTE_TEST_T18 | IW_ROUTE_TEST_T19 : (IW_APP_##app == IW_APP_TIMER || IW_APP_##app == IW_APP_STOPWATCH) ? IW_ROUTE_TEST_T16 | IW_ROUTE_TEST_T17 : IW_ROUTE_TEST_T13 | IW_ROUTE_TEST_T14) : 0, \
     (IW_PAGE_##id == IW_PAGE_DIAGNOSTICS || IW_PAGE_##id == IW_PAGE_TIMER_DETAIL || IW_PAGE_##id == IW_PAGE_ALARM_EDIT || IW_PAGE_##id == IW_PAGE_ALERT_TIMER || IW_PAGE_##id == IW_PAGE_ALERT_ALARM || IW_PAGE_##id == IW_PAGE_NOTIFICATION_DETAIL) ? IW_ROUTE_PARAMS_ID : IW_ROUTE_##support == IW_ROUTE_READY ? IW_ROUTE_PARAMS_NONE : IW_ROUTE_PARAMS_RESERVED, \
     IW_ROUTE_##support == IW_ROUTE_READY ? IW_ROUTE_RESOURCE_BUILTIN : IW_ROUTE_RESOURCE_NONE, #id, #id}
static const iw_route_descriptor_t routes[] = {
    PAGE(FACE, SYSTEM, 0, 0, READY, FRESH),
    PAGE(LAUNCHER_LIST, SYSTEM, 0, 0, READY, POSITION),
    PAGE(LAUNCHER_GRID, SYSTEM, IW_PAGE_LAUNCHER_LIST, 0, READY, POSITION),
    PAGE(SETTINGS, SETTINGS, IW_PAGE_LAUNCHER_LIST, 0, READY, POSITION),
    PAGE(DISPLAY, SETTINGS, IW_PAGE_SETTINGS, 0, READY, POSITION),
    PAGE(BRIGHTNESS, SETTINGS, IW_PAGE_DISPLAY, 0, READY, FRESH),
    PAGE(TIME, SETTINGS, IW_PAGE_SETTINGS, 0, READY, DRAFT),
    PAGE(LOCALE, SETTINGS, IW_PAGE_SETTINGS, 0, RESERVED, FRESH),
    PAGE(ABOUT, SETTINGS, IW_PAGE_SETTINGS, 0, READY, FRESH),
    PAGE(ACCESSIBILITY, SETTINGS, IW_PAGE_SETTINGS, 0, RESERVED, FRESH),
    PAGE(TIMER_LIST, TIMER, IW_PAGE_LAUNCHER_LIST, 0, READY, POSITION),
    PAGE(TIMER_CREATE, TIMER, IW_PAGE_TIMER_LIST, 0, RESERVED, DRAFT),
    PAGE(TIMER_DETAIL, TIMER, IW_PAGE_TIMER_LIST, 0, READY, FRESH),
    PAGE(ALERT_TIMER, SYSTEM, 0, 0, READY, FRESH),
    PAGE(ALERT_ALARM, SYSTEM, 0, 0, READY, FRESH),
    PAGE(STOPWATCH, STOPWATCH, IW_PAGE_LAUNCHER_LIST, 0, READY, FRESH),
    PAGE(STOPWATCH_LAPS, STOPWATCH, IW_PAGE_STOPWATCH, 0, RESERVED, POSITION),
    PAGE(ALARM_LIST, ALARM, IW_PAGE_LAUNCHER_LIST, 0, READY, POSITION),
    PAGE(ALARM_EDIT, ALARM, IW_PAGE_ALARM_LIST, 0, READY, DRAFT),
    PAGE(CONTROL_CENTER, SYSTEM, 0, 0, READY, FRESH),
    PAGE(NOTIFICATION_LIST, SYSTEM, IW_PAGE_FACE, 0, READY, POSITION),
    PAGE(NOTIFICATION_DETAIL, SYSTEM, IW_PAGE_NOTIFICATION_LIST, 0, READY, POSITION),
    PAGE(SMART_STACK, SYSTEM, IW_PAGE_FACE, 0, READY, POSITION),
    PAGE(SWITCHER, SYSTEM, 0, 0, READY, POSITION),
    PAGE(LOCK, SYSTEM, 0, 0, READY, FRESH),
    PAGE(WATER_LOCK, SYSTEM, 0, 0, READY, FRESH),
    PAGE(FACE_PICKER, SYSTEM, IW_PAGE_FACE, 0, READY, POSITION),
    PAGE(FACE_EDITOR, SYSTEM, IW_PAGE_FACE_PICKER, 0, READY, DRAFT),
    PAGE(POWER_SHEET, SYSTEM, 0, 0, OVERLAY, FRESH),
    PAGE(ACTIVITY, HEALTH, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(HEART_RATE, HEALTH, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(BLOOD_OXYGEN, HEALTH, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(WORKOUT_TYPES, WORKOUT, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, POSITION),
    PAGE(WORKOUT_ACTIVE, WORKOUT, IW_PAGE_WORKOUT_TYPES, 0, RESERVED, FRESH),
    PAGE(WORKOUT_SUMMARY, WORKOUT, IW_PAGE_WORKOUT_TYPES, 0, RESERVED, POSITION),
    PAGE(CALENDAR, CALENDAR, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, POSITION),
    PAGE(CALCULATOR, CALCULATOR, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(PHOTO_GRID, PHOTOS, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, POSITION),
    PAGE(PHOTO_VIEWER, PHOTOS, IW_PAGE_PHOTO_GRID, 0, RESERVED, POSITION),
    PAGE(MINDFULNESS, MINDFULNESS, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(WEATHER_DEMO, OFFLINE, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(WALLET_DEMO, OFFLINE, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(COMMUNICATION_DEMO, OFFLINE, IW_PAGE_LAUNCHER_LIST, 0, RESERVED, FRESH),
    PAGE(COMPONENT_GALLERY, DIAGNOSTICS, 0, 0, RESERVED, FRESH),
    PAGE(DIAGNOSTICS, DIAGNOSTICS, IW_PAGE_LAUNCHER_GRID, 0, READY, POSITION),
    PAGE(RECOVERY, SYSTEM, 0, 0, OVERLAY, FRESH)
};
#undef PAGE

size_t iw_route_count(void) { return sizeof(routes) / sizeof(routes[0]); }
const iw_route_descriptor_t *iw_route_at(size_t index)
{
    return index < iw_route_count() ? &routes[index] : NULL;
}
const iw_route_descriptor_t *iw_route_find(uint16_t page_id)
{
    /* 表按固定 ID 排序；二分查找无分配、无缓存失效问题。 */
    size_t first = 0, end = iw_route_count();
    while (first < end) {
        size_t middle = first + (end - first) / 2;
        if (routes[middle].page_id < page_id) first = middle + 1;
        else end = middle;
    }
    return first < iw_route_count() && routes[first].page_id == page_id ? &routes[first] : NULL;
}
bool iw_route_equal(iw_route_t left, iw_route_t right)
{
    return left.page_id == right.page_id && left.argument == right.argument;
}
